### PR TITLE
Adds some more bash / cli aliases

### PR DESCRIPTION
**Pull request by sandeepraju**
source: personal bashrc + www

### CODE REVIEW

**Comment by sandeepraju** [comment]
@stocarul oops, saw this issue https://github.com/algotech/dotaliases/issues/25 now.

Let me know if you want me to add these as well; I would love to..

**Comment by stocarul** [comment]
@sandeepraju: I see that you added most of them. The only missing one is: `apt-get: sudo apt-get`. It would be great if you can add it and also update the documentation: https://github.com/algotech/dotaliases/blob/master/doc/bash/cli_aliases.md Thank you!

**Comment by stocarul** [comment]
@sandeepraju: Did you have time to check my comment? Please let me know if you are still interested in finishing it.

**Comment by sandeepraju** [comment]
@stocarul done!

**Comment by stocarul** [comment]
Merged.

**Pull request closed without merging**
