### PR TITLE
Add aliases for Apache

### LINKED ISSUE #49: Aliases for apache
It would be great to have aliases for different apache tasks, starting from the following list:
- **apsta**: `sudo service apache2 start`
- **apsto**: `sudo service apache2 stop`
- **apres**: `sudo service apache2 restart`

More should be added.

### PR DESCRIPTION
**Pull request by calina-c**
- Add aliases for Apache
- Closes #49

### CODE REVIEW

**Comment by stocarul** [comment]
@calina-c: Is the `doc/apache_aliases.md` file in the correct folder? I think it should be in `doc/bash/` as you linked it in `README.md`?

**Comment by stocarul** [comment]
@calina-c: Why did you add the `bash/.DS_Store` file? Please amend this commit and remove that file.

**Comment by calina-c** [comment]
Handled comments in new commit.

**Comment by stocarul** [comment]
@calina-c: It seems like the `bash/apache_aliases` is not loaded. Does it work on your computer? Please update the following file accordingly: https://github.com/algotech/dotaliases/blob/master/bash_aliases

**Comment by calina-c** [comment]
@stocarul Fixed in the last commit.

**Review by stocarul — APPROVED** [review]
👍

**Pull request merged**
