### PR TITLE
Add git push --force-with-lease alias

### LINKED ISSUE #71: [Git] Force with lease
I believe it would be useful to have an alias for pushing with the `--force-with-lease` option.

### PR DESCRIPTION
**Pull request by calina-c**
Adds alias and documentation for this. Closes #71.

### CODE REVIEW

**Comment by stocarul** [comment]
@calina-c: I suggest to add 2 aliases instead of 1, with the following name:
- `gpofl`: for origin
- `gpufl`: for upstream

**Comment by calina-c** [comment]
Done in last commit. GPOFL kind of sounds like: http://cdn.bulbagarden.net/upload/thumb/8/8b/WTP_EP045.png/200px-WTP_EP045.png

**Comment by stocarul** [comment]
@calina-c: Please merge master into this branch.

**Comment by calina-c** [comment]
@stocarul Merged master.

**Pull request merged**
