### PR TITLE
Adds Magento 2 aliases

### PR DESCRIPTION
**Pull request by ofonimefrancis**

### CODE REVIEW

**Review by dandinu — APPROVED** [review]

**Comment by stocarul** [comment]
@dandinu: Thank you for the change and sorry for my late reply. Your changes look great. We only need 2 small fixes before merging your PR:
 - the new lines from the end of the file should be removed
 - the documentation for this aliases should also be included. See the following example for the Django aliases: https://github.com/algotech/dotaliases/blob/master/doc/bash/django_aliases.md

**Comment by dandinu** [comment]
@opiumated

**Comment by ofonimefrancis** [comment]
Thanks @dandinu . @stocarul  the required changes has been made in my recent commit. Please review and if there are anymore updates you'd like to see, i'd gladly add them. I work with magento all day, and this little utility would save a lot of me typing php bin/magento.

**Review by stocarul — APPROVED** [review]
Awesome work!

**Pull request merged**
