### PR TITLE
Adds some more git aliases

### PR DESCRIPTION
**Pull request by sandeepraju**
source: http://haacked.com/archive/2014/07/28/github-flow-aliases/

### CODE REVIEW

**Comment by stocarul** [comment]
@sandeepraju: Thank you for updating the aliases. In order to merge this request, could you also update the documentation in this file https://github.com/algotech/dotaliases/blob/master/doc/git/git_aliases.md ?

**Comment by sandeepraju** [comment]
done!

**Comment by sandeepraju** [comment]
bump.

**Comment by stocarul** [comment]
Merged. Thank you @sandeepraju.

**Pull request closed without merging**
